web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./nginx.conf:/etc/nginx/nginx.conf
    links:
        - php

php:
    image: php:7-fpm
    volumes:
        - ./code:/code